abstract class RoutePath {
  static const String HOME_PAGE = "/";
  static const String LOGIN_PAGE = '/login'; // 登录页
  static const String LOGIN_BY_CODE_PAGE = '/login_by_code'; // 登录页
  static const String REGISTER_PAGE = '/register'; // 注册页
  static const String RESET_PASSWORD_PAGE = '/reset_password'; // 重置密码页
  static const String SETTING_PAGE = '/setting'; // 设置页
  static const String UPDATE_PAGE = '/update_list'; // 更新说明页
  static const String PROMOTION_PAGE = "/promotion"; // 推广
  static const String ARTICLE_DETAIL_PAGE = "/article_detail"; // 推广
  static const String MY_INFO_PAGE = "/my_info"; // 用户信息
  static const String SEARCH_PAGE = "/search"; // 用户信息
  static const String FORECAST_LIST_PAGE = "/forecast_list"; // 比分预测列表
  static const String PERSONAL_CENTER_PAGE = "/personal_center"; // 我的文章页
  static const String MINE_ASSETS_PAGE = "/mine_assets"; // 我的资产页
  static const String MINE_ORDER_PAGE = "/mine_order"; // 我的消费页
  static const String MINE_FAVORITE_PAGE = "/mine_favorite"; // 我的关注页
  static const String MINE_MESSAGE_PAGE = "/mine_message"; // 我的消息页
  static const String MINE_ARENA_PAGE = "/mine_arena"; // 我的擂台
  static const String ARENA_LOTTERY_PAGE = "/arena_lottery"; // 擂台竞猜
  static const String CREATE_ARENA_PAGE = "/create_arena"; // 擂台竞猜
  static const String ARTICLE_COMMENT_PAGE = "/article_comment"; // 文章评论
  static const String CURRENCY_RECHARGE_PAGE = "/currency_recharge"; // 掌门币充值
  static const String MAGIC_BEANS_RECHARGE_PAGE = "/magic_beans_recharge"; // 魔豆充值
  static const String WITHDRAW_PAGE = "/withdraw"; // 提现
  static const String WITHDRAW_LIST_PAGE = "/withdraw_list"; // 提现列表
  static const String BANK_CARD_PAGE = "/bank_card"; // 银行卡
  static const String ADD_BANK_CARD_PAGE = "/add_bank_card"; // 添加银行卡
  static const String CHECK_BANK_CARD_PAGE = "/check_bank_card"; // 添加银行卡信息
  static const String FORECAST_DETAIL_PAGE = "/forecast_detail"; //
  static const String ARENA_RANKING_PAGE = "/arena_ranking"; // 擂台榜单
  static const String ABOUT_US_PAGE = "/about_us"; // 关于我们
  static const String PAY_PAGE = "/pay"; // 支付页面
  static const String PAY_RESULT_PAGE = "/pay_result"; // 支付结果页面
  static const String WEBVIEW_PAGE = "/webview"; // WEB页面
  static const String CREATE_TOPIC_PAGE = "/create_topic"; // 发布帖子
  static const String REPORT_PAGE = "/report"; // 举报
  static const String COMMUNITY_DETAIL_PAGE = "/community_detail"; // 社区帖子详情
}
